name: Merge to master
on:
  push:
    branches: [master]
jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.1"

      - name: Get Flutter packages
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - name: Build APK
        env:
          KEY_JKS: ${{ secrets.ANDROID_KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ANDROID_ALIAS_PASSWORD }}
        run: echo $KEY_JKS | base64 -d > android/acme-flutter-keystore.jks && flutter build apk --release --split-per-abi

      - name: Upload v7a APK
        uses: actions/upload-artifact@v2
        with:
          name: app-armeabi-v7a-release.apk
          path: build/app/outputs/apk/release/app-armeabi-v7a-release.apk

      - name: Upload arm64 APK
        uses: actions/upload-artifact@v2
        with:
          name: app-arm64-v8a-release.apk
          path: build/app/outputs/apk/release/app-arm64-v8a-release.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v2
        with:
          name: app-x86_64-release.apk
          path: build/app/outputs/apk/release/app-x86_64-release.apk
