name: Merge to master
on:
  push:
    branches: [master]
jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "1.8"

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.17.1"
        env:
          KEY_JKS: ${{ secrets.ANDROID_KEY_JKS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          ALIAS_PASSWORD: ${{ secrets.ANDROID_ALIAS_PASSWORD }}
          run: echo $KEY_JKS > acme-flutter-keystore.jks && flutter build apk --release --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: build/app/outputs/apk/release/*.apk
